### PR TITLE
Update zh_cn.json

### PR DESCRIPTION
**Pull request by ChuijkYahus**

### CODE REVIEW

**Comment by wendall911** [comment]
@ChuijkYahus I did a release for this just now. Thanks for the contribution!

I wanted to also ask if you play any of our other mods? 

I could use some help cleaning up a poor translation in our other Tinkers' mod. There was some offensive wording that I fixed, but I don't think the quality is very good. I have help in our other mods, but if you are willing I'd like help with this specific one.

**Comment by ChuijkYahus** [comment]
I don't usually include them ingame, sorry.
I'm completely OK with all changes and helps. (Though may I ask what these helps actually are?)

**Comment by wendall911** [comment]
Looking for some help with translations for this: https://github.com/wendall911/TinkerSurvival/tree/1.18.2/src/main/resources/assets/tinkersurvival/lang

**Comment by Cactusstudent** [comment]
For TinkerSurvival, the Chinese Translation is truely poor and low quality. Maybe I can help you correct this? (I done the Chinese Translation of TiC3, so if you don't believe me, you can go there and verify)

**Comment by wendall911** [comment]
@Cactusstudent Thank you for the offer of help. It would be very appreciated if you could help. Now that we have a lot more people using the translations, I want to have them fixed so they are better. TiC3 was probably tough to translate! Great job on that.

**Pull request merged**
