### PR TITLE
Make Soul Stained modifier do the cool thing

### PR DESCRIPTION
**Pull request by SammySemicolon**
!!!
I have quite frankly no idea how I managed to load the game using lodestone 1.4.1 and TCIntegrations, given that the directory of LodestoneAttributeRegistry has changed but whatever !!!

### CODE REVIEW

**Comment by SammySemicolon** [comment]
Ok so this is rlly confusing my IDE seems to have still been using 1.3.0 lodestone while writing the commit which means the game now crashes anytime u hold a soul-stained tool once again. Let me try and fix that?

**Comment by SammySemicolon** [comment]
OKay nvm it was correctly using Lodestone 1.4.1, but for 1.19.2 rather than 1.18.2 sobbing

**Comment by SammySemicolon** [comment]
I fixed it up, and tested in game. Works fine :)

**Comment by SammySemicolon** [comment]
As a sidenote, including the magic damage amount in the tooltip of the weapon, alongside regular damage, would be appreciated.

**Comment by wendall911** [comment]
Awesome, thanks! I'll work on this tomorrow and get a new release out. I'll add the magic damage to the tooltip as well.

**Pull request merged**
