### PR TITLE
Added support for several mods

### PR DESCRIPTION
**Pull request by vizthex123**
There's a few important notes in a couple of the messages, so please check those. I think I did tag additions wrong (never added them with Forge's method before), so It'd be nice if they were double-checked first.

## Support List
- Create _(The Windows & Panes need the `forge:glass/silica` tag so Tinker's can auto-add them to the melting recipes for Glass)_
- Create Crafts & Additions
- Create Deco
- Create Enchantment Industry
- Essentials
- Obscuria's Essentials (Legacy)
- Quark _(Dirty Glass and its Pane need the `forge:glass/silica` tag so Tinker's can auto-add them to the melting recipes for Glass)_
- The Iron Ladder from Twilight Forest

### CODE REVIEW

**Comment by wendall911** [comment]
This isn't a valid PR. This looks like something you might want to add to your modpack. It is far outside of the scope of this mod. If this was going to be a part of the mod and a valid PR, I would need the actual code change, not the output files. I regenerate those before each release.

**Comment by vizthex123** [comment]
Damn, wish I'd known that before spending 4 hours on it...

I guess I can publish it as a datapack or something (but those don't get as many downloads).

Melting recipes should still be added for mods that you're adding materials for imo. As I said, it's not really fully integrated without them.

**Comment by wendall911** [comment]
@vizthex123 in the path is has "generated" anytime you see this it is because it is using code to generate those files. I check them into the repo as a reference to the build. This would be fine as a datapack. There is another mod called Materialis that focuses on materials. They haven't been active in a while, but given that everything, especially in 1.19.2 is datapack driven, it will be easy to have a datapack just for this type of thing. What I'm doing with this mod is capabilities that match the integration mod stuff, not materials (unless necessary). It's all in the mod description if you read that.

**Comment by vizthex123** [comment]
looks like that adds a bunch of materials instead of just melting recipes, but alright.

anyway, if you could add melting recipes for all the materials this mod adds it'd be noice. That's kinda why i opened this PR, after all.

**Comment by wendall911** [comment]
If it is for a specific mod integration it happens. But if you read the mod description:

The main goal here is to not just add a bunch of random new materials from mods and call it "integration". The goal is to add materials where it makes sense, and capture the capabilities of other mods tools and armors in Tinkers' Construct. This started with Botania and wanting to have the ability to use mana generating inventory items to automatically repair tools. This entire concept has worked out well, and the idea moving forward is balanced integration.

That said, I may do another mod like Materialis to address this, but in the meanwhile, you'll need to do this via datapack. I really like the Global Packs mod for this, makes it super simple, and you can use the json files you've generated.

**Comment by vizthex123** [comment]
i use openloader (since it also does resource packs), but i interpreted the page as "i'll add materials and melting recipes for any mods i support".

anyway, it's not a big deal. I've published the pack, so let's hope people use it lol.

**Pull request closed without merging**
